### ISSUE TITLE
Debugger bug when displaying memory

### ISSUE THREAD

**Issue by psyker156** [CommunicationsSecurityEstablishment/spartacus#24]
I believe PR https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/17 introduced a bug in the debugger. Memory subsystem is currently changing a lot. Trying to display memory using the "m" command in the debugger currently results in:
```
Next instruction to be executed:
0x40000000 : MOV #0x400004fb $A 
('testFiles/LoneBall/LoneBall.bin',): m 0x40000000 4 hex
m 0x40000000 4 hex
Displaying 4 bytes from address 0x40000000
Traceback (most recent call last):
  File "Debugger.py", line 127, in <module>
    symbolsFile=symbolsFile)
  File "/home/user/spartacus/ToolChain/Debugger/Debugger.py", line 102, in __init__
    self.debug(inputFile=inputFile)
  File "/home/user/spartacus/ToolChain/Debugger/Debugger.py", line 252, in debug
    self.runUserCommand(command=userCommand)
  File "/home/user/spartacus/ToolChain/Debugger/Debugger.py", line 495, in runUserCommand
    displayFormat=brokenCommand[3])
  File "/home/user/spartacus/ToolChain/Debugger/Debugger.py", line 426, in displayMemoryInFormat
    valueString = hex(memSlice[i]._value)
AttributeError: 'int' object has no attribute '_value'
```

**Comment by psyker156** [comment]
This is fixed in PR
https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/25

**Comment by pg-cse** [comment]
This was indeed fixed by https://github.com/CommunicationsSecurityEstablishment/spartacus/pull/25
The PR was just merged in please update your copies of Spartacus.
